language: php

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

env:
  global:
    - COMPOSER_ARGS="--no-interaction"

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.3
    - php: 7.4

services: mongodb

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install $COMPOSER_ARGS
  - composer show
  - if ! nc -z localhost 27017; then sudo service mongod start; fi
  - cp ./tests/application.config.php ./config/

script:
  - ./vendor/bin/doctrine-module odm:schema:create
  - ./vendor/bin/doctrine-module odm:schema:drop
  - if [[ $TEST_COVERAGE == 'true' ]]; then ./vendor/bin/phpunit --coverage-clover clover.xml ; else ./vendor/bin/phpunit ; fi
  - if [[ $CHECK_CS == 'true' ]]; then ./vendor/bin/phpcs --standard=PSR2 ./src/ ./tests/ ./config/ ; fi
